use errors::Result;

#[tokio::main]
async fn main() -> Result<()> {
    Ok(())
}
